In [1]:
# How to open and analyze the CSV file created by compute_graph_metrics.py
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

csv_path = '/home/gabrimi8/RDL/ReDeLEx/graph_metrics_test_hubs_bridges.csv'
df = pd.read_csv(csv_path)

print("\nAvailable columns:")
print(df.columns.tolist())
# df.head()

Available columns:
['dataset', 'num_hubs', 'num_bridges', 'default_nodes', 'default_edges', 'processed_nodes', 'processed_edges', 'delta_nodes', 'delta_edges', 'default_diameter', 'default_avg_diameter', 'processed_diameter', 'processed_avg_diameter', 'delta_diameter', 'delta_avg_diameter', 'default_max_degree', 'default_avg_degree', 'processed_max_degree', 'processed_avg_degree', 'delta_max_degree', 'delta_avg_degree', 'default_density', 'processed_density', 'delta_density', 'default_node2edge_ratio', 'processed_node2edge_ratio', 'delta_node2edge_ratio', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']

In [2]:

# Find top 5 datasets for a specific metric
metric_column = 'delta_diameter'
top_5_highest = df.nlargest(5, metric_column)[['dataset', metric_column]]
print(f"\nTop 5 datasets with HIGHEST {metric_column}:")
print(top_5_highest.to_string(index=False))

top_5_lowest = df.nsmallest(5, metric_column)[['dataset', metric_column]]
print(f"\nTop 5 datasets with LOWEST {metric_column}:")
print(top_5_lowest.to_string(index=False))

Top 5 datasets with HIGHEST delta_diameter:
            dataset  delta_diameter
      ctu-accidents               0
ctu-atherosclerosis               0
            ctu-cde               0
          ctu-chess               0
      ctu-craftbeer               0

Top 5 datasets with LOWEST delta_diameter:
           dataset  delta_diameter
       ctu-mondial              -3
         rel-trial              -2
ctu-adventureworks              -2
         ctu-dunur              -2
          ctu-elti              -2

In [22]:
filtered = df[
    (df["num_hubs"] > 1) &
    (df["num_bridges"] > 0) &
    (df["default_diameter"] > 0) &
    (df["delta_diameter"] <= 0) &
    (df["processed_hubs_bridges_ratio"] < 10) &
    (df["normalized_hubs_bridges_ratio"] < 1)
]
filtered

# adventureworks, ncaa

# adventureworks - hodně hubs a bridges, dobry processed a normalized ratio
# mondial - hodně hubs a bridges, největší delta diameter -3
# ncaa - nemusí být ideální - nodes z 9 -> 3, ale může ukázat nedostatky
# sakila - nemusí být ideální - processed hubs bridge ration 3.00

# f1, avito, stack

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
3,rel-f1,2,3,9,13,4,10,-5,-3,3,1.58,2,1.00,-1,-0.58,6,2.89,8,5.00,2,2.11,0.18,0.83,0.65,0.69,0.40,-0.29,1.00,0.56
8,ctu-adventureworks,10,18,71,90,53,124,-18,34,9,4.19,7,3.05,-2,-1.13,18,2.69,23,5.06,5,2.37,0.02,0.04,0.03,0.79,0.43,-0.36,1.56,0.39
29,ctu-ergastf1,2,7,14,21,6,18,-8,-3,3,1.84,2,1.17,-1,-0.67,10,3.00,13,6.00,3,3.00,0.12,0.60,0.48,0.67,0.33,-0.33,1.12,0.64
44,ctu-mondial,12,7,34,63,17,74,-17,11,5,2.36,2,1.63,-3,-0.72,25,3.71,42,8.71,17,5.00,0.06,0.27,0.22,0.54,0.23,-0.31,1.12,0.56
50,ctu-ncaa,4,2,9,17,3,15,-6,-2,4,1.58,2,0.89,-2,-0.69,11,3.78,19,10.00,8,6.22,0.24,2.50,2.26,0.53,0.20,-0.33,1.00,0.67
55,ctu-sakila,2,7,16,22,13,28,-3,6,7,2.83,5,2.10,-2,-0.74,5,2.93,9,4.67,4,1.73,0.09,0.18,0.09,0.73,0.46,-0.26,3.00,0.56
69,ctu-tpcds,9,4,24,102,17,580,-7,478,4,1.77,2,1.13,-2,-0.64,22,8.50,142,68.24,120,59.74,0.18,2.13,1.95,0.24,0.03,-0.21,1.86,0.54

In [4]:

corr = df.drop("dataset", axis=1).corr()

In [5]:
csv_path = '/home/gabrimi8/RDL/ReDeLEx/graph_metrics_test_bridges.csv'
df_b = pd.read_csv(csv_path)


print("\nAvailable columns:")
print(df_b.columns.tolist())
df_b.head()

Available columns:
['dataset', 'num_hubs', 'num_bridges', 'default_nodes', 'default_edges', 'processed_nodes', 'processed_edges', 'delta_nodes', 'delta_edges', 'default_diameter', 'default_avg_diameter', 'processed_diameter', 'processed_avg_diameter', 'delta_diameter', 'delta_avg_diameter', 'default_max_degree', 'default_avg_degree', 'processed_max_degree', 'processed_avg_degree', 'delta_max_degree', 'delta_avg_degree', 'default_density', 'processed_density', 'delta_density', 'default_node2edge_ratio', 'processed_node2edge_ratio', 'delta_node2edge_ratio', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
0,rel-amazon,0,1,3,2,2,1,-1,-1,2,0.89,1,0.50,-1,-0.39,2,1.33,1,1.00,-1,-0.33,0.33,0.50,0.17,1.50,2.00,0.50,1.00,0.33
1,rel-avito,1,4,8,11,5,9,-3,-2,2,1.41,2,0.96,0,-0.45,5,2.75,5,3.60,0,0.85,0.20,0.45,0.25,0.73,0.56,-0.17,1.33,0.50
2,rel-event,0,3,5,7,2,4,-3,-3,2,1.12,1,0.50,-1,-0.62,5,2.80,5,4.00,0,1.20,0.35,2.00,1.65,0.71,0.50,-0.21,1.00,0.60
3,rel-f1,2,3,9,13,6,10,-3,-3,3,1.58,2,1.17,-1,-0.41,6,2.89,6,3.33,0,0.44,0.18,0.33,0.15,0.69,0.60,-0.09,1.00,0.33
4,rel-hm,0,1,3,2,2,1,-1,-1,2,0.89,1,0.50,-1,-0.39,2,1.33,1,1.00,-1,-0.33,0.33,0.50,0.17,1.50,2.00,0.50,1.00,0.33

In [10]:
number = 20
metric_column = 'num_bridges'
top_n_highest = df_b.nlargest(number, metric_column)[['dataset', metric_column, 'default_nodes', 'processed_nodes', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']]
print(f"\nTop {number} datasets with HIGHEST {metric_column}:")
print(top_n_highest.to_string(index=False))


# df_b.sort_values(metric_column, ascending=False)

# satellite - vysoký bridge/node ratio = 0.89 (extrémní případ)
# lahman, hokey - střední bridge/node ratio ~ 0.4
# mesh, geneea - malé bridge/node ratio ~ 0.2
# northwind - obecně známý dataset, 4 bridge z toho 3 processnutý

# trial, f1

Top 20 datasets with HIGHEST num_bridges:
           dataset  num_bridges  default_nodes  processed_nodes  processed_hubs_bridges_ratio  normalized_hubs_bridges_ratio
        ctu-mooney           67             68                1                          1.00                           0.99
     ctu-satellite           32             36                4                          1.00                           0.89
ctu-adventureworks           18             71               59                          1.50                           0.25
         ctu-dunur           16             17                1                          1.00                           0.94
          ctu-elti           10             11                1                          1.00                           0.91
        ctu-lahman           10             25               15                          1.00                           0.40
        ctu-hockey            8             22               14                          1.00                           0.36
      ctu-ergastf1            7             14                8                          1.17                           0.50
       ctu-mondial            7             34               28                          1.17                           0.21
        ctu-sakila            7             16               14                          3.50                           0.44
          ctu-mesh            6             29               23                          1.00                           0.21
         rel-trial            5             15               10                          1.00                           0.33
        ctu-grants            5             12                7                          1.00                           0.42
         rel-avito            4              8                5                          1.33                           0.50
         rel-stack            4              7                3                          1.00                           0.57
        ctu-geneea            4             19               15                          1.00                           0.21
     ctu-northwind            4             13               10                          1.33                           0.31
         ctu-stats            4              8                4                          1.00                           0.50
         ctu-tpcds            4             24               24                           NaN                           0.17
         rel-event            3              5                2                          1.00                           0.60

In [11]:
filtered = df_b[
    (df_b["num_hubs"] >= 0 ) &
    (df_b["num_bridges"] > 1) &
    (df_b["default_diameter"] > 3) &
    (df_b["delta_diameter"] <= -2) &
    (df_b["processed_hubs_bridges_ratio"] < 10) &
    (df_b["normalized_hubs_bridges_ratio"] < 0.5)
]
filtered

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
6,rel-trial,0,5,15,15,10,10,-5,-5,4,2.16,2,1.62,-2,-0.54,10,2.00,10,2.00,0,0.00,0.07,0.11,0.04,1.00,1.00,0.00,1.00,0.33
34,ctu-geneea,0,4,19,20,15,16,-4,-4,7,3.02,5,2.48,-2,-0.54,5,2.11,5,2.13,0,0.03,0.06,0.08,0.02,0.95,0.94,-0.01,1.00,0.21
37,ctu-grants,0,5,12,11,7,6,-5,-5,4,2.31,2,1.47,-2,-0.84,6,1.83,6,1.71,0,-0.12,0.08,0.14,0.06,1.09,1.17,0.08,1.00,0.42
38,ctu-hepatitis,0,3,7,6,4,3,-3,-3,4,1.96,2,1.12,-2,-0.83,3,1.71,3,1.50,0,-0.21,0.14,0.25,0.11,1.17,1.33,0.17,1.00,0.43
40,ctu-imdb,0,2,7,6,5,4,-2,-2,5,2.04,3,1.44,-2,-0.60,3,1.71,3,1.60,0,-0.11,0.14,0.20,0.06,1.17,1.25,0.08,1.00,0.29
41,ctu-lahman,0,10,25,31,15,21,-10,-10,6,2.60,4,2.31,-2,-0.28,14,2.48,14,2.80,0,0.32,0.05,0.10,0.05,0.81,0.71,-0.09,1.00,0.40
46,ctu-movielens,0,3,7,6,4,3,-3,-3,4,1.96,2,1.12,-2,-0.83,3,1.71,3,1.50,0,-0.21,0.14,0.25,0.11,1.17,1.33,0.17,1.00,0.43
50,ctu-ncaa,4,2,9,17,7,15,-2,-2,4,1.58,2,1.31,-2,-0.27,11,3.78,11,4.29,0,0.51,0.24,0.36,0.12,0.53,0.47,-0.06,1.00,0.22
51,ctu-northwind,1,4,13,13,10,11,-3,-2,7,3.15,5,2.36,-2,-0.79,4,2.00,4,2.20,0,0.20,0.08,0.12,0.04,1.00,0.91,-0.09,1.33,0.31
55,ctu-sakila,2,7,16,22,14,25,-2,3,7,2.83,5,2.19,-2,-0.64,5,2.93,8,3.85,3,0.91,0.09,0.14,0.05,0.73,0.56,-0.17,3.50,0.44
73,ctu-visualgenome,0,2,6,5,4,3,-2,-2,4,1.72,2,1.12,-2,-0.60,3,1.67,3,1.50,0,-0.17,0.17,0.25,0.08,1.20,1.33,0.13,1.00,0.33

In [12]:
csv_path = '/home/gabrimi8/RDL/ReDeLEx/graph_metrics_test_hubs.csv'
df_h = pd.read_csv(csv_path)

print("\nAvailable columns:")
print(df_h.columns.tolist())
df_h.head()

Available columns:
['dataset', 'num_hubs', 'num_bridges', 'default_nodes', 'default_edges', 'processed_nodes', 'processed_edges', 'delta_nodes', 'delta_edges', 'default_diameter', 'default_avg_diameter', 'processed_diameter', 'processed_avg_diameter', 'delta_diameter', 'delta_avg_diameter', 'default_max_degree', 'default_avg_degree', 'processed_max_degree', 'processed_avg_degree', 'delta_max_degree', 'delta_avg_degree', 'default_density', 'processed_density', 'delta_density', 'default_node2edge_ratio', 'processed_node2edge_ratio', 'delta_node2edge_ratio', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
0,rel-amazon,0,1,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
1,rel-avito,1,4,8,11,8,14,0,3,2,1.41,2,1.31,0,-0.09,5,2.75,5,3.50,0,0.75,0.20,0.25,0.05,0.73,0.57,-0.16,NaN,0.12
2,rel-event,0,3,5,7,5,7,0,0,2,1.12,2,1.12,0,0.00,5,2.80,5,2.80,0,0.00,0.35,0.35,0.00,0.71,0.71,0.00,NaN,0.00
3,rel-f1,2,3,9,13,7,13,-2,0,3,1.58,2,1.31,-1,-0.27,6,2.89,8,3.71,2,0.83,0.18,0.31,0.13,0.69,0.54,-0.15,1.0,0.22
4,rel-hm,0,1,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00

In [15]:
number = 20
metric_column = 'num_hubs'
top_n_highest = df_h.nlargest(number, metric_column)[['dataset', metric_column, 'default_nodes', 'processed_nodes', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']]
print(f"\nTop {number} datasets with HIGHEST {metric_column}:")
print(top_n_highest.to_string(index=False))

df_h.sort_values(metric_column, ascending=False)

# sales - Prime example - 1 hub/link table  se nahradí edges
# mondial, tpcds - hodně hubs, hodně processed, ratio ~ 0.38
# ergastf1 - ratio ~ 0.14

# f1

Top 20 datasets with HIGHEST num_hubs:
           dataset  num_hubs  default_nodes  processed_nodes  processed_hubs_bridges_ratio  normalized_hubs_bridges_ratio
       ctu-mondial        12             34               23                          1.09                           0.35
ctu-adventureworks        10             71               65                          1.67                           0.14
         ctu-tpcds         9             24               17                          1.29                           0.38
ctu-carcinogenesis         4              6                2                          1.00                           0.67
          ctu-ncaa         4              9                5                          1.00                           0.44
            rel-f1         2              9                7                          1.00                           0.22
      ctu-ergastf1         2             14               12                          1.00                           0.14
        ctu-sakila         2             16               15                          2.00                           0.12
         rel-avito         1              8                8                           NaN                           0.12
         rel-stack         1              7                7                           NaN                           0.14
       ctu-airline         1             19               18                          1.00                           0.05
        ctu-credit         1              8                7                          1.00                           0.12
     ctu-northwind         1             13               13                           NaN                           0.08
ctu-premiereleague         1              4                3                          1.00                           0.25
         ctu-sales         1              4                3                          1.00                           0.25
         ctu-stats         1              8                8                           NaN                           0.12
    ctu-toxicology         1              4                3                          1.00                           0.25
        rel-amazon         0              3                3                           NaN                           0.00
         rel-event         0              5                5                           NaN                           0.00
            rel-hm         0              3                3                           NaN                           0.00

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
44,ctu-mondial,12,7,34,63,23,79,-11,16,5,2.36,4,1.93,-1,-0.43,25,3.71,41,6.87,16,3.16,0.06,0.16,0.10,0.54,0.29,-0.25,1.09,0.35
8,ctu-adventureworks,10,18,71,90,65,130,-6,40,9,4.19,8,3.52,-1,-0.67,18,2.69,21,4.26,3,1.58,0.02,0.03,0.01,0.79,0.50,-0.29,1.67,0.14
69,ctu-tpcds,9,4,24,102,17,576,-7,474,4,1.77,2,1.13,-2,-0.64,22,8.50,140,67.76,118,59.26,0.18,2.12,1.93,0.24,0.03,-0.21,1.29,0.38
50,ctu-ncaa,4,2,9,17,5,17,-4,0,4,1.58,3,1.28,-1,-0.30,11,3.78,19,6.80,8,3.02,0.24,0.85,0.61,0.53,0.29,-0.24,1.00,0.44
15,ctu-carcinogenesis,4,0,6,13,2,13,-4,0,2,1.17,1,0.50,-1,-0.67,9,4.33,17,13.00,8,8.67,0.43,6.50,6.07,0.46,0.15,-0.31,1.00,0.67
3,rel-f1,2,3,9,13,7,13,-2,0,3,1.58,2,1.31,-1,-0.27,6,2.89,8,3.71,2,0.83,0.18,0.31,0.13,0.69,0.54,-0.15,1.00,0.22
55,ctu-sakila,2,7,16,22,15,25,-1,3,7,2.83,7,2.68,0,-0.15,5,2.93,8,3.57,3,0.64,0.09,0.12,0.03,0.73,0.60,-0.13,2.00,0.12
29,ctu-ergastf1,2,7,14,21,12,23,-2,2,3,1.84,2,1.56,-1,-0.28,10,3.00,13,3.83,3,0.83,0.12,0.17,0.06,0.67,0.52,-0.14,1.00,0.14
22,ctu-credit,1,1,8,9,7,9,-1,0,3,1.66,2,1.35,-1,-0.31,5,2.25,6,2.57,1,0.32,0.16,0.21,0.05,0.89,0.78,-0.11,1.00,0.12
53,ctu-premiereleague,1,1,4,5,3,5,-1,0,2,1.00,1,0.67,-1,-0.33,3,2.50,4,3.33,1,0.83,0.42,0.83,0.42,0.80,0.60,-0.20,1.00,0.25
5,rel-stack,1,4,7,12,7,15,0,3,3,1.39,3,1.39,0,0.00,10,3.43,14,4.29,4,0.86,0.29,0.36,0.07,0.58,0.47,-0.12,NaN,0.14
1,rel-avito,1,4,8,11,8,14,0,3,2,1.41,2,1.31,0,-0.09,5,2.75,5,3.50,0,0.75,0.20,0.25,0.05,0.73,0.57,-0.16,NaN,0.12
9,ctu-airline,1,0,19,33,18,528,-1,495,2,1.80,1,0.94,-1,-0.85,33,3.47,128,58.67,95,55.19,0.10,1.73,1.63,0.58,0.03,-0.54,1.00,0.05
51,ctu-northwind,1,4,13,13,13,16,0,3,7,3.15,7,2.92,0,-0.22,4,2.00,6,2.46,2,0.46,0.08,0.10,0.02,1.00,0.81,-0.19,NaN,0.08
66,ctu-toxicology,1,0,4,5,3,5,-1,0,2,1.00,1,0.67,-1,-0.33,3,2.50,5,3.33,2,0.83,0.42,0.83,0.42,0.80,0.60,-0.20,1.00,0.25
63,ctu-stats,1,4,8,13,8,16,0,3,3,1.50,3,1.50,0,0.00,10,3.25,12,4.00,2,0.75,0.23,0.29,0.05,0.62,0.50,-0.12,NaN,0.12
56,ctu-sales,1,0,4,3,3,3,-1,0,2,1.12,1,0.67,-1,-0.46,3,1.50,2,2.00,-1,0.50,0.25,0.50,0.25,1.33,1.00,-0.33,1.00,0.25
13,ctu-biodegradability,0,2,5,5,5,5,0,0,3,1.44,3,1.44,0,0.00,4,2.00,4,2.00,0,0.00,0.25,0.25,0.00,1.00,1.00,0.00,NaN,0.00
6,rel-trial,0,5,15,15,15,15,0,0,4,2.16,4,2.16,0,0.00,10,2.00,10,2.00,0,0.00,0.07,0.07,0.00,1.00,1.00,0.00,NaN,0.00
7,ctu-accidents,0,1,3,3,3,3,0,0,1,0.67,1,0.67,0,0.00,2,2.00,2,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
2,rel-event,0,3,5,7,5,7,0,0,2,1.12,2,1.12,0,0.00,5,2.80,5,2.80,0,0.00,0.35,0.35,0.00,0.71,0.71,0.00,NaN,0.00
4,rel-hm,0,1,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
0,rel-amazon,0,1,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
12,ctu-basketballwomen,0,2,8,8,8,8,0,0,4,1.94,4,1.94,0,0.00,6,2.00,6,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
11,ctu-basketballmen,0,2,9,9,9,9,0,0,5,2.27,5,2.27,0,0.00,5,2.00,5,2.00,0,0.00,0.12,0.12,0.00,1.00,1.00,0.00,NaN,0.00
10,ctu-atherosclerosis,0,0,4,3,4,3,0,0,2,1.12,2,1.12,0,0.00,3,1.50,3,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
18,ctu-classicmodels,0,2,8,8,8,8,0,0,6,2.38,6,2.38,0,0.00,4,2.00,4,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
19,ctu-cora,0,1,3,3,3,3,0,0,2,0.89,2,0.89,0,0.00,3,2.00,3,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
16,ctu-cde,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
14,ctu-bupa,0,1,9,8,9,8,0,0,3,1.73,3,1.73,0,0.00,7,1.78,7,1.78,0,0.00,0.11,0.11,0.00,1.12,1.12,0.00,NaN,0.00
28,ctu-employee,0,2,6,6,6,6,0,0,3,1.44,3,1.44,0,0.00,4,2.00,4,2.00,0,0.00,0.20,0.20,0.00,1.00,1.00,0.00,NaN,0.00
30,ctu-expenditures,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
32,ctu-fnhk,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
31,ctu-financial,0,1,8,8,8,8,0,0,3,1.72,3,1.72,0,0.00,5,2.00,5,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
34,ctu-geneea,0,4,19,20,19,20,0,0,7,3.02,7,3.02,0,0.00,5,2.11,5,2.11,0,0.00,0.06,0.06,0.00,0.95,0.95,0.00,NaN,0.00
35,ctu-genes,0,1,3,3,3,3,0,0,2,0.89,2,0.89,0,0.00,3,2.00,3,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
36,ctu-gosales,0,1,5,4,5,4,0,0,3,1.44,3,1.44,0,0.00,3,1.60,3,1.60,0,0.00,0.20,0.20,0.00,1.25,1.25,0.00,NaN,0.00
33,ctu-ftp,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
21,ctu-craftbeer,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
20,ctu-countries,0,1,4,3,4,3,0,0,3,1.25,3,1.25,0,0.00,2,1.50,2,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
24,ctu-dcg,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
23,ctu-dallas,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
25,ctu-diabetes,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
26,ctu-dunur,0,16,17,32,17,32,0,0,2,1.77,2,1.77,0,0.00,32,3.76,32,3.76,0,0.00,0.12,0.12,0.00,0.53,0.53,0.00,NaN,0.00
27,ctu-elti,0,10,11,20,11,20,0,0,2,1.65,2,1.65,0,0.00,20,3.64,20,3.64,0,0.00,0.18,0.18,0.00,0.55,0.55,0.00,NaN,0.00
17,ctu-chess,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
45,ctu-mooney,0,67,68,134,68,134,0,0,2,1.94,2,1.94,0,0.00,134,3.94,134,3.94,0,0.00,0.03,0.03,0.00,0.51,0.51,0.00,NaN,0.00
43,ctu-mesh,0,6,29,33,29,33,0,0,3,1.93,3,1.93,0,0.00,32,2.28,32,2.28,0,0.00,0.04,0.04,0.00,0.88,0.88,0.00,NaN,0.00
42,ctu-legalacts,0,2,5,5,5,5,0,0,3,1.44,3,1.44,0,0.00,4,2.00,4,2.00,0,0.00,0.25,0.25,0.00,1.00,1.00,0.00,NaN,0.00
41,ctu-lahman,0,10,25,31,25,31,0,0,6,2.60,6,2.60,0,0.00,14,2.48,14,2.48,0,0.00,0.05,0.05,0.00,0.81,0.81,0.00,NaN,0.00
39,ctu-hockey,0,8,22,26,22,26,0,0,4,2.08,4,2.08,0,0.00,14,2.74,14,2.74,0,0.00,0.06,0.06,0.00,0.85,0.85,0.00,NaN,0.00
40,ctu-imdb,0,2,7,6,7,6,0,0,5,2.04,5,2.04,0,0.00,3,1.71,3,1.71,0,0.00,0.14,0.14,0.00,1.17,1.17,0.00,NaN,0.00
38,ctu-hepatitis,0,3,7,6,7,6,0,0,4,1.96,4,1.96,0,0.00,3,1.71,3,1.71,0,0.00,0.14,0.14,0.00,1.17,1.17,0.00,NaN,0.00
37,ctu-grants,0,5,12,11,12,11,0,0,4,2.31,4,2.31,0,0.00,6,1.83,6,1.83,0,0.00,0.08,0.08,0.00,1.09,1.09,0.00,NaN,0.00
52,ctu-pima,0,0,9,8,9,8,0,0,2,1.58,2,1.58,0,0.00,8,1.78,8,1.78,0,0.00,0.11,0.11,0.00,1.12,1.12,0.00,NaN,0.00
47,ctu-musklarge,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
54,ctu-restbase,0,1,3,3,3,3,0,0,1,0.67,1,0.67,0,0.00,2,2.00,2,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
57,ctu-samegen,0,3,4,6,4,6,0,0,2,1.12,2,1.12,0,0.00,6,3.00,6,3.00,0,0.00,0.50,0.50,0.00,0.67,0.67,0.00,NaN,0.00
58,ctu-sap,0,0,5,3,5,3,0,0,2,1.06,2,1.06,0,0.00,3,1.50,3,1.50,0,0.00,0.15,0.15,0.00,1.67,1.67,0.00,NaN,0.00
48,ctu-musksmall,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
49,ctu-mutagenesis,0,1,3,3,3,3,0,0,2,0.89,2,0.89,0,0.00,3,2.00,3,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
46,ctu-movielens,0,3,7,6,7,6,0,0,4,1.96,4,1.96,0,0.00,3,1.71,3,1.71,0,0.00,0.14,0.14,0.00,1.17,1.17,0.00,NaN,0.00
61,ctu-sfscores,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
60,ctu-seznam,0,0,4,3,4,3,0,0,2,1.12,2,1.12,0,0.00,3,1.50,3,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
59,ctu-satellite,0,32,36,65,36,65,0,0,4,1.90,4,1.90,0,0.00,34,3.61,34,3.61,0,0.00,0.05,0.05,0.00,0.55,0.55,0.00,NaN,0.00
62,ctu-shakespeare,0,1,4,3,4,3,0,0,3,1.25,3,1.25,0,0.00,2,1.50,2,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
65,ctu-thrombosis,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
64,ctu-studentloan,0,1,10,9,10,9,0,0,3,1.76,3,1.76,0,0.00,8,1.80,8,1.80,0,0.00,0.10,0.10,0.00,1.11,1.11,0.00,NaN,0.00
67,ctu-tpcc,0,3,9,10,9,10,0,0,4,1.98,4,1.98,0,0.00,3,2.22,3,2.22,0,0.00,0.14,0.14,0.00,0.90,0.90,0.00,NaN,0.00
68,ctu-tpcd,0,1,8,8,8,8,0,0,4,1.91,4,1.91,0,0.00,3,2.00,3,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
70,ctu-tpch,0,2,8,8,8,8,0,0,4,1.91,4,1.91,0,0.00,3,2.00,3,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
71,ctu-triazine,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
72,ctu-uwcse,0,2,4,4,4,4,0,0,3,1.25,3,1.25,0,0.00,3,2.00,3,2.00,0,0.00,0.33,0.33,0.00,1.00,1.00,0.00,NaN,0.00
73,ctu-visualgenome,0,2,6,5,6,5,0,0,4,1.72,4,1.72,0,0.00,3,1.67,3,1.67,0,0.00,0.17,0.17,0.00,1.20,1.20,0.00,NaN,0.00
74,ctu-voc,0,0,8,7,8,7,0,0,2,1.53,2,1.53,0,0.00,7,1.75,7,1.75,0,0.00,0.12,0.12,0.00,1.14,1.14,0.00,NaN,0.00
75,ctu-walmart,0,0,4,3,4,3,0,0,3,1.25,3,1.25,0,0.00,2,1.50,2,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
76,ctu-webkp,0,1,3,3,3,3,0,0,2,0.89,2,0.89,0,0.00,3,2.00,3,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
77,ctu-world,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00