In [2]:
# How to open and analyze the CSV file created by compute_graph_metrics.py
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

csv_path = '/home/gabrimi8/RDL/ReDeLEx/graph_metrics_info_hubs_bridges.csv'
df = pd.read_csv(csv_path)

print("\nAvailable columns:")
print(df.columns.tolist())
# df.head()

Available columns:
['dataset', 'num_hubs', 'num_bridges', 'default_nodes', 'default_edges', 'processed_nodes', 'processed_edges', 'delta_nodes', 'delta_edges', 'default_diameter', 'default_avg_diameter', 'processed_diameter', 'processed_avg_diameter', 'delta_diameter', 'delta_avg_diameter', 'default_max_degree', 'default_avg_degree', 'processed_max_degree', 'processed_avg_degree', 'delta_max_degree', 'delta_avg_degree', 'default_density', 'processed_density', 'delta_density', 'default_node2edge_ratio', 'processed_node2edge_ratio', 'delta_node2edge_ratio', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']

In [6]:

# Find top 5 datasets for a specific metric
metric_column = 'delta_diameter'
top_5_highest = df.nlargest(5, metric_column)[['dataset', metric_column]]
print(f"\nTop 5 datasets with HIGHEST {metric_column}:")
print(top_5_highest.to_string(index=False))

top_5_lowest = df.nsmallest(5, metric_column)[['dataset', metric_column]]
print(f"\nTop 5 datasets with LOWEST {metric_column}:")
print(top_5_lowest.to_string(index=False))

Top 5 datasets with HIGHEST delta_diameter:
            dataset  delta_diameter
      ctu-accidents               0
ctu-atherosclerosis               0
            ctu-cde               0
          ctu-chess               0
      ctu-craftbeer               0

Top 5 datasets with LOWEST delta_diameter:
           dataset  delta_diameter
       ctu-mondial              -3
ctu-adventureworks              -2
         ctu-dunur              -2
          ctu-elti              -2
        ctu-geneea              -2

In [ ]:
filtered = df[
    (df["num_hubs"] > 1) &
    (df["num_bridges"] > 1) &
    (df["default_diameter"] > 3) &
    (df["delta_diameter"] <= -1) &
    (df["processed_hubs_bridges_ratio"] < 10) &
    (df["normalized_hubs_bridges_ratio"] < 1)
]
filtered

# adventureworks, ncaa

# adventureworks - hodně hubs a bridges, dobry processed a normalized ratio
# mondial - hodně hubs a bridges, největší delta diameter -3
# ncaa - nemusí být ideální - nodes z 9 -> 3, ale může ukázat nedostatky
# sakila - nemusí být ideální - processed hubs bridge ration 3.00

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
1,ctu-adventureworks,10,18,71,90,53,124,-18,34,9,4.19,7,3.05,-2,-1.13,18,2.69,23,5.06,5,2.37,0.02,0.04,0.03,0.79,0.43,-0.36,1.56,0.39
37,ctu-mondial,12,7,34,63,17,49,-17,-14,5,2.36,2,1.63,-3,-0.72,25,3.71,23,5.76,-2,2.06,0.06,0.18,0.12,0.54,0.35,-0.19,1.12,0.56
43,ctu-ncaa,4,2,9,17,3,6,-6,-11,4,1.58,2,0.89,-2,-0.69,11,3.78,7,4.00,-4,0.22,0.24,1.00,0.76,0.53,0.50,-0.03,1.00,0.67
48,ctu-sakila,2,7,16,22,13,26,-3,4,7,2.83,5,2.10,-2,-0.74,5,2.93,8,4.33,3,1.40,0.09,0.17,0.07,0.73,0.50,-0.23,3.00,0.56
62,ctu-tpcds,9,4,24,102,17,580,-7,478,4,1.77,2,1.13,-2,-0.64,22,8.50,142,68.24,120,59.74,0.18,2.13,1.95,0.24,0.03,-0.21,1.86,0.54

In [16]:

corr = df.drop("dataset", axis=1).corr()
corr

,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
num_hubs,1.000000,0.117700,0.523210,0.591944,0.615147,0.464314,-0.231802,0.343860,0.407046,0.398922,0.255868,0.284760,-0.419024,-0.257850,0.161808,0.602119,0.471736,0.423248,0.311131,0.385048,-0.214202,0.272669,0.392685,-0.406795,-0.518775,-0.367429,0.247646,0.285855
num_bridges,0.117700,1.000000,0.803649,0.806265,0.149971,0.006151,-0.986251,-0.222476,0.187245,0.352716,-0.029575,-0.035930,-0.421848,-0.637189,0.920083,0.387022,0.008530,-0.006296,-0.628295,-0.051461,-0.391192,-0.199708,-0.065798,-0.400265,-0.227502,0.309522,-0.034586,0.603259
default_nodes,0.523210,0.803649,1.000000,0.918076,0.696920,0.273804,-0.822637,0.040975,0.515775,0.669765,0.328635,0.386903,-0.524077,-0.563396,0.765410,0.490637,0.283451,0.204114,-0.274888,0.162563,-0.589868,-0.171398,0.046384,-0.499303,-0.445942,0.002101,0.090565,0.473118
default_edges,0.591944,0.806265,0.918076,1.000000,0.526865,0.474482,-0.844800,0.239045,0.366851,0.510366,0.139328,0.186210,-0.519625,-0.583346,0.821512,0.717019,0.484448,0.442314,-0.133445,0.392213,-0.482067,0.062033,0.263993,-0.554220,-0.490420,0.013209,0.125150,0.541644
processed_nodes,0.615147,0.149971,0.696920,0.526865,1.000000,0.418679,-0.165565,0.312026,0.667082,0.724273,0.650976,0.734165,-0.326374,-0.161159,0.151970,0.282613,0.423153,0.310392,0.274370,0.300729,-0.532874,-0.116038,0.085434,-0.311614,-0.430683,-0.359625,0.258293,0.027451
processed_edges,0.464314,0.006151,0.273804,0.474482,0.418679,1.000000,-0.044590,0.968168,0.116321,0.183807,0.034350,0.096110,-0.180050,-0.167577,0.205518,0.635195,0.991472,0.990211,0.746927,0.989980,-0.181639,0.549682,0.688356,-0.330147,-0.457660,-0.381527,0.176708,0.038979
delta_nodes,-0.231802,-0.986251,-0.822637,-0.844800,-0.165565,-0.044590,1.000000,0.191032,-0.180403,-0.346823,0.064176,0.050002,0.461939,0.646993,-0.932083,-0.450647,-0.054309,-0.034607,0.595542,0.014871,0.388696,0.143703,0.003948,0.439572,0.271792,-0.288006,0.083590,-0.628853
delta_edges,0.343860,-0.222476,0.040975,0.239045,0.312026,0.968168,0.191032,1.000000,0.023998,0.057633,-0.001726,0.053069,-0.050856,-0.018978,-0.006892,0.496791,0.955927,0.966517,0.861869,0.980508,-0.063288,0.588708,0.684250,-0.206588,-0.365388,-0.424613,0.159505,-0.111019
default_diameter,0.407046,0.187245,0.515775,0.366851,0.667082,0.116321,-0.180403,0.023998,1.000000,0.931793,0.872536,0.837007,-0.649974,-0.361390,0.048295,0.261996,0.118277,0.060057,0.072669,0.034300,-0.696710,-0.290268,-0.045615,-0.446184,-0.478948,-0.188445,0.423195,0.288457
default_avg_diameter,0.398922,0.352716,0.669765,0.510366,0.724273,0.183807,-0.346823,0.057633,0.931793,1.000000,0.758937,0.800325,-0.689773,-0.526429,0.268899,0.363386,0.197309,0.123554,-0.008945,0.090762,-0.840840,-0.341690,-0.044831,-0.579420,-0.570913,-0.122342,0.347078,0.395343
processed_diameter,0.255868,-0.029575,0.328635,0.139328,0.650976,0.034350,0.064176,-0.001726,0.872536,0.758937,1.000000,0.922665,-0.195849,0.047174,-0.167660,-0.014808,0.023842,-0.033462,0.137260,-0.034168,-0.565728,-0.336699,-0.150071,-0.142706,-0.265495,-0.328256,0.451739,-0.107127
processed_avg_diameter,0.284760,-0.035930,0.386903,0.186210,0.734165,0.096110,0.050002,0.053069,0.837007,0.800325,0.922665,1.000000,-0.244832,0.088424,-0.107668,0.030561,0.119680,0.027518,0.181725,0.026094,-0.701003,-0.367706,-0.130404,-0.214023,-0.337512,-0.347057,0.368129,-0.130373
delta_diameter,-0.419024,-0.421848,-0.524077,-0.519625,-0.326374,-0.180050,0.461939,-0.050856,-0.649974,-0.689773,-0.195849,-0.244832,1.000000,0.798774,-0.357740,-0.548921,-0.200323,-0.172599,0.067648,-0.121998,0.518451,0.058889,-0.141882,0.673612,0.548375,-0.132359,-0.074470,-0.745639
delta_avg_diameter,-0.257850,-0.637189,-0.563396,-0.583346,-0.161159,-0.167577,0.646993,-0.018978,-0.361390,-0.526429,0.047174,0.088424,0.798774,1.000000,-0.599145,-0.560481,-0.156634,-0.164980,0.273675,-0.112415,0.403043,0.046908,-0.109740,0.659179,0.469808,-0.289126,0.035615,-0.842245
default_max_degree,0.161808,0.920083,0.765410,0.821512,0.151970,0.205518,-0.932083,-0.006892,0.048295,0.268899,-0.167660,-0.107668,-0.357740,-0.599145,1.000000,0.473875,0.227247,0.202556,-0.487426,0.162779,-0.384404,-0.059175,0.088243,-0.437297,-0.287206,0.248522,-0.091853,0.516107
default_avg_degree,0.602119,0.387022,0.490637,0.717019,0.282613,0.635195,-0.450647,0.496791,0.261996,0.363386,-0.014808,0.030561,-0.548921,-0.560481,0.473875,1.000000,0.663241,0.671188,0.267144,0.605299,-0.320860,0.454599,0.637883,-0.803199,-0.745657,-0.062543,0.207195,0.685394
processed_max_degree,0.471736,0.008530,0.283451,0.484448,0.423153,0.991472,-0.054309,0.955927,0.118277,0.197309,0.023842,0.119680,-0.200323,-0.156634,0.227247,0.663241,1.000000,0.987232,0.739554,0.983548,-0.221596,0.544485,0.698219,-0.374173,-0.495354,-0.377533,0.160153,0.061534
processed_avg_degree,0.423248,-0.006296,0.204114,0.442314,0.310392,0.990211,-0.034607,0.966517,0.060057,0.123554,-0.033462,0.027518,-0.172599,-0.164980,0.202556,0.671188,0.987232,1.000000,0.745172,0.996333,-0.146300,0.603016,0.733585,-0.356173,-0.473153,-0.363086,0.174614,0.076434
delta_max_degree,0.311131,-0.628295,-0.274888,-0.133445,0.274370,0.746927,0.595542,0.861869,0.072669,-0.008945,0.137260,0.181725,0.067648,0.273675,-0.487426,0.267144,0.739554,0.745172,1.000000,0.769362,0.067004,0.529098,0.565047,-0.033241,-0.245635,-0.510278,0.202754,-0.301551
delta_avg_degree,0.385048,-0.051461,0.162563,0.392213,0.300729,0.989980,0.014871,0.980508,0.034300,0.090762,-0.034168,0.026094,-0.121998,-0.112415,0.162779,0.605299,0.983548,0.996333,0.769362,1.000000,-0.120087,0.595015,0.714072,-0.289728,-0.421991,-0.382675,0.165648,0.002923
default_density,-0.214202,-0.391192,-0.589868,-0.482067,-0.532874,-0.181639,0.388696,-0.063288,-0.696710,-0.840840,-0.565728,-0.701003,0.518451,0.403043,-0.384404,-0.320860,-0.221596,-0.146300,0.067004,-0.120087,1.000000,0.460053,0.113303,0.505300,0.440013,-0.031084,-0.166812,-0.281445
processed_density,0.272669,-0.199708,-0.171398,0.062033,-0.116038,0.549682,0.143703,0.588708,-0.290268,-0.341690,-0.336699,-0.367706,0.058889,0.046908,-0.059175,0.454599,0.544485,0.603016,0.529098,0.595015,0.460053,1.000000,0.934263,-0.217259,-0.353257,-0.376125,-0.004642,0.112136
delta_density,0.392685,-0.065798,0.046384,0.263993,0.085434,0.688356,0.003948,0.684250,-0.045615,-0.044831,-0.150071,-0.130404,-0.141882,-0.109740,0.088243,0.637883,0.698219,0.733585,0.565047,0.714072,0.113303,0.934263,1.000000,-0.446395,-0.572383,-0.408546,0.049787,0.238504
default_node2edge_ratio,-0.406795,-0.400265,-0.499303,-0.554220,-0.311614,-0.330147,0.439572,-0.206588,-0.446184,-0.579420,-0.142706,-0.214023,0.673612,0.659179,-0.437297,-0.803199,-0.374173,-0.356173,-0.033241,-0.289728,0.505300,-0.217259,-0.446395,1.000000,0.907308,0.027185,-0.191280,-0.782044
processed_node2edge_ratio,-0.518775,-0.227502,-0.445942,-0.490420,-0.430683,-0.457660,0.271792,-0.365388,-0.478948,-0.570913,-0.265495,-0.337512,0.548375,0.469808,-0.287206,-0.745657,-0.495354,-0.473153,-0.245635,-0.421991,0.440013,-0.353257,-0.572383,0.907308,1.000000,0.444947,-0.420384,-0.593854
delta_node2edge_ratio,-0.367429,0.309522,0.002101,0.013209,-0.359625,-0.381527,-0.288006,-0.424613,-0.188445,-0.122342,-0.328256,-0.347057,-0.132359,-0.289126,0.248522,-0.062543,-0.377533,-0.363086,-0.510278,-0.382675,-0.031084,-0.376125,-0.408546,0.027185,0.444947,1.000000,-0.448585,0.252867
processed_hubs_bridges_ratio,0.247646,-0.034586,0.090565,0.125150,0.258293,0.176708,0.083590,0.159505,0.423195,0.347078,0.451739,0.368129,-0.074470,0.035615,-0.091853,0.207195,0.160153,0.174614,0.202754,0.165648,-0.166812,-0.004642,0.049787,-0.191280,-0.420384,-0.448585,1.000000,0.022034
normalized_hubs_bridges_ratio,0.285855,0.603259,0.473118,0.541644,0.027451,0.038979,-0.628853,-0.111019,0.288457,0.395343,-0.107127,-0.130373,-0.745639,-0.842245,0.516107,0.685394,0.061534,0.076434,-0.301551,0.002923,-0.281445,0.112136,0.238504,-0.782044,-0.593854,0.252867,0.022034,1.000000

In [2]:
csv_path = '/home/gabrimi8/RDL/ReDeLEx/graph_metrics_info_bridges.csv'
df_b = pd.read_csv(csv_path)

csv_test = '/home/gabrimi8/RDL/ReDeLEx/graph_metrics_test_bridges.csv'
df_test = pd.read_csv(csv_test)

print("\nAvailable columns:")
print(df_b.columns.tolist())
df_b.head()

Available columns:
['dataset', 'num_hubs', 'num_bridges', 'default_nodes', 'default_edges', 'processed_nodes', 'processed_edges', 'delta_nodes', 'delta_edges', 'default_diameter', 'default_avg_diameter', 'processed_diameter', 'processed_avg_diameter', 'delta_diameter', 'delta_avg_diameter', 'default_max_degree', 'default_avg_degree', 'processed_max_degree', 'processed_avg_degree', 'delta_max_degree', 'delta_avg_degree', 'default_density', 'processed_density', 'delta_density', 'default_node2edge_ratio', 'processed_node2edge_ratio', 'delta_node2edge_ratio', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
0,ctu-accidents,0,1,3,3,2,2,-1,-1,1,0.67,1,0.50,0,-0.17,2,2.00,2,2.00,0,0.00,0.50,1.00,0.50,1.00,1.00,0.00,1.0,0.33
1,ctu-adventureworks,10,18,71,90,59,84,-12,-6,9,4.19,8,3.53,-1,-0.66,18,2.69,20,3.05,2,0.37,0.02,0.02,0.01,0.79,0.70,-0.09,1.5,0.25
2,ctu-airline,1,0,19,33,19,33,0,0,2,1.80,2,1.80,0,0.00,33,3.47,33,3.47,0,0.00,0.10,0.10,0.00,0.58,0.58,0.00,NaN,0.00
3,ctu-atherosclerosis,0,0,4,3,4,3,0,0,2,1.12,2,1.12,0,0.00,3,1.50,3,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
4,ctu-basketballmen,0,2,9,9,7,7,-2,-2,5,2.27,4,1.88,-1,-0.39,5,2.00,5,2.00,0,0.00,0.12,0.17,0.04,1.00,1.00,0.00,1.0,0.22

In [ ]:
number = 20
metric_column = 'num_bridges'
top_n_highest = df_b.nlargest(number, metric_column)[['dataset', metric_column, 'default_nodes', 'processed_nodes', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']]
print(f"\nTop {number} datasets with HIGHEST {metric_column}:")
print(top_n_highest.to_string(index=False))


# df_b.sort_values(metric_column, ascending=False)

# (satellite) - vysoký bridge/node ratio = 0.89 (extrémní případ)
# lahman, hokey - střední bridge/node ratio ~ 0.4
# mesh, geneea - malé bridge/node ratio ~ 0.2
# northwind - obecně známý dataset, 4 bridge z toho 3 processnutý

Top 20 datasets with HIGHEST num_bridges:
           dataset  num_bridges  default_nodes  processed_nodes  processed_hubs_bridges_ratio  normalized_hubs_bridges_ratio
        ctu-mooney           67             68                1                          1.00                           0.99
     ctu-satellite           32             36                4                          1.00                           0.89
ctu-adventureworks           18             71               59                          1.50                           0.25
         ctu-dunur           16             17                1                          1.00                           0.94
          ctu-elti           10             11                1                          1.00                           0.91
        ctu-lahman           10             25               15                          1.00                           0.40
        ctu-hockey            8             22               14                          1.00                           0.36
      ctu-ergastf1            7             14                8                          1.17                           0.50
       ctu-mondial            7             34               28                          1.17                           0.21
        ctu-sakila            7             16               14                          3.50                           0.44
          ctu-mesh            6             29               23                          1.00                           0.21
        ctu-grants            5             12                7                          1.00                           0.42
        ctu-geneea            4             19               15                          1.00                           0.21
     ctu-northwind            4             13               10                          1.33                           0.31
         ctu-stats            4              8                4                          1.00                           0.50
         ctu-tpcds            4             24               24                           NaN                           0.17
     ctu-hepatitis            3              7                4                          1.00                           0.43
     ctu-movielens            3              7                4                          1.00                           0.43
       ctu-samegen            3              4                1                          1.00                           0.75
          ctu-tpcc            3              9                7                          1.50                           0.33

In [27]:
filtered = df_b[
    (df_b["num_hubs"] >= 0 ) &
    (df_b["num_bridges"] > 1) &
    (df_b["default_diameter"] > 3) &
    (df_b["delta_diameter"] <= -2) &
    (df_b["processed_hubs_bridges_ratio"] < 10) &
    (df_b["normalized_hubs_bridges_ratio"] < 0.5)
]
filtered

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
27,ctu-geneea,0,4,19,20,15,16,-4,-4,7,3.02,5,2.48,-2,-0.54,5,2.11,5,2.13,0,0.03,0.06,0.08,0.02,0.95,0.94,-0.01,1.00,0.21
30,ctu-grants,0,5,12,11,7,6,-5,-5,4,2.31,2,1.47,-2,-0.84,6,1.83,6,1.71,0,-0.12,0.08,0.14,0.06,1.09,1.17,0.08,1.00,0.42
31,ctu-hepatitis,0,3,7,6,4,3,-3,-3,4,1.96,2,1.12,-2,-0.83,3,1.71,3,1.50,0,-0.21,0.14,0.25,0.11,1.17,1.33,0.17,1.00,0.43
33,ctu-imdb,0,2,7,6,5,4,-2,-2,5,2.04,3,1.44,-2,-0.60,3,1.71,3,1.60,0,-0.11,0.14,0.20,0.06,1.17,1.25,0.08,1.00,0.29
34,ctu-lahman,0,10,25,31,15,16,-10,-15,6,2.60,4,2.31,-2,-0.28,14,2.48,9,2.13,-5,-0.35,0.05,0.08,0.02,0.81,0.94,0.13,1.00,0.40
39,ctu-movielens,0,3,7,6,4,3,-3,-3,4,1.96,2,1.12,-2,-0.83,3,1.71,3,1.50,0,-0.21,0.14,0.25,0.11,1.17,1.33,0.17,1.00,0.43
44,ctu-northwind,1,4,13,13,10,11,-3,-2,7,3.15,5,2.36,-2,-0.79,4,2.00,4,2.20,0,0.20,0.08,0.12,0.04,1.00,0.91,-0.09,1.67,0.38
66,ctu-visualgenome,0,2,6,5,4,3,-2,-2,4,1.72,2,1.12,-2,-0.60,3,1.67,3,1.50,0,-0.17,0.17,0.25,0.08,1.20,1.33,0.13,1.00,0.33

In [3]:
csv_path = '/home/gabrimi8/RDL/ReDeLEx/graph_metrics_info_hubs.csv'
df_h = pd.read_csv(csv_path)

print("\nAvailable columns:")
print(df_h.columns.tolist())
df_h.head()

Available columns:
['dataset', 'num_hubs', 'num_bridges', 'default_nodes', 'default_edges', 'processed_nodes', 'processed_edges', 'delta_nodes', 'delta_edges', 'default_diameter', 'default_avg_diameter', 'processed_diameter', 'processed_avg_diameter', 'delta_diameter', 'delta_avg_diameter', 'default_max_degree', 'default_avg_degree', 'processed_max_degree', 'processed_avg_degree', 'delta_max_degree', 'delta_avg_degree', 'default_density', 'processed_density', 'delta_density', 'default_node2edge_ratio', 'processed_node2edge_ratio', 'delta_node2edge_ratio', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
0,ctu-accidents,0,1,3,3,3,3,0,0,1,0.67,1,0.67,0,0.00,2,2.00,2,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
1,ctu-adventureworks,10,18,71,90,65,130,-6,40,9,4.19,8,3.52,-1,-0.67,18,2.69,21,4.26,3,1.58,0.02,0.03,0.01,0.79,0.50,-0.29,1.67,0.14
2,ctu-airline,1,0,19,33,18,528,-1,495,2,1.80,1,0.94,-1,-0.85,33,3.47,128,58.67,95,55.19,0.10,1.73,1.63,0.58,0.03,-0.54,1.00,0.05
3,ctu-atherosclerosis,0,0,4,3,4,3,0,0,2,1.12,2,1.12,0,0.00,3,1.50,3,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
4,ctu-basketballmen,0,2,9,9,9,9,0,0,5,2.27,5,2.27,0,0.00,5,2.00,5,2.00,0,0.00,0.12,0.12,0.00,1.00,1.00,0.00,NaN,0.00

In [6]:
metric_column = 'num_hubs'
top_5_highest = df_h.nlargest(20, metric_column)[['dataset', metric_column, 'num_bridges', 'default_nodes', 'processed_nodes', 'processed_hubs_bridges_ratio', 'normalized_hubs_bridges_ratio']]
print(f"\nTop 5 datasets with HIGHEST {metric_column}:")
print(top_5_highest.to_string(index=False))

df_h.sort_values(metric_column, ascending=False)

# sales - Prime example - 1 hub/link table  se nahradí edges
# mondial, tpcds - hodně hubs, hodně processed, ratio ~ 0.38
# ergastf1 - ratio ~ 0.14

Top 5 datasets with HIGHEST num_hubs:
             dataset  num_hubs  num_bridges  default_nodes  processed_nodes  processed_hubs_bridges_ratio  normalized_hubs_bridges_ratio
         ctu-mondial        12            7             34               23                          1.09                           0.35
  ctu-adventureworks        10           18             71               65                          1.67                           0.14
           ctu-tpcds         9            4             24               17                          1.29                           0.38
  ctu-carcinogenesis         4            0              6                2                          1.00                           0.67
            ctu-ncaa         4            2              9                5                          1.00                           0.44
        ctu-ergastf1         2            7             14               12                          1.00                           0.14
          ctu-sakila         2            7             16               15                          2.00                           0.12
         ctu-airline         1            0             19               18                          1.00                           0.05
          ctu-credit         1            1              8                7                          1.00                           0.12
       ctu-northwind         1            4             13               13                           NaN                           0.08
  ctu-premiereleague         1            1              4                3                          1.00                           0.25
           ctu-sales         1            0              4                3                          1.00                           0.25
           ctu-stats         1            4              8                8                           NaN                           0.12
      ctu-toxicology         1            0              4                3                          1.00                           0.25
       ctu-accidents         0            1              3                3                           NaN                           0.00
 ctu-atherosclerosis         0            0              4                4                           NaN                           0.00
   ctu-basketballmen         0            2              9                9                           NaN                           0.00
 ctu-basketballwomen         0            2              8                8                           NaN                           0.00
ctu-biodegradability         0            2              5                5                           NaN                           0.00
            ctu-bupa         0            1              9                9                           NaN                           0.00

,dataset,num_hubs,num_bridges,default_nodes,default_edges,processed_nodes,processed_edges,delta_nodes,delta_edges,default_diameter,default_avg_diameter,processed_diameter,processed_avg_diameter,delta_diameter,delta_avg_diameter,default_max_degree,default_avg_degree,processed_max_degree,processed_avg_degree,delta_max_degree,delta_avg_degree,default_density,processed_density,delta_density,default_node2edge_ratio,processed_node2edge_ratio,delta_node2edge_ratio,processed_hubs_bridges_ratio,normalized_hubs_bridges_ratio
37,ctu-mondial,12,7,34,63,23,55,-11,-8,5,2.36,4,1.93,-1,-0.43,25,3.71,23,4.78,-2,1.08,0.06,0.11,0.05,0.54,0.42,-0.12,1.09,0.35
1,ctu-adventureworks,10,18,71,90,65,130,-6,40,9,4.19,8,3.52,-1,-0.67,18,2.69,21,4.26,3,1.58,0.02,0.03,0.01,0.79,0.50,-0.29,1.67,0.14
62,ctu-tpcds,9,4,24,102,17,576,-7,474,4,1.77,2,1.13,-2,-0.64,22,8.50,140,67.76,118,59.26,0.18,2.12,1.93,0.24,0.03,-0.21,1.29,0.38
8,ctu-carcinogenesis,4,0,6,13,2,4,-4,-9,2,1.17,1,0.50,-1,-0.67,9,4.33,5,4.00,-4,-0.33,0.43,2.00,1.57,0.46,0.50,0.04,1.00,0.67
43,ctu-ncaa,4,2,9,17,5,8,-4,-9,4,1.58,3,1.28,-1,-0.30,11,3.78,7,3.20,-4,-0.58,0.24,0.40,0.16,0.53,0.62,0.10,1.00,0.44
48,ctu-sakila,2,7,16,22,15,24,-1,2,7,2.83,7,2.68,0,-0.15,5,2.93,7,3.43,2,0.50,0.09,0.11,0.02,0.73,0.62,-0.10,2.00,0.12
22,ctu-ergastf1,2,7,14,21,12,20,-2,-1,3,1.84,2,1.56,-1,-0.28,10,3.00,11,3.33,1,0.33,0.12,0.15,0.04,0.67,0.60,-0.07,1.00,0.14
44,ctu-northwind,1,4,13,13,13,16,0,3,7,3.15,7,2.92,0,-0.22,4,2.00,6,2.46,2,0.46,0.08,0.10,0.02,1.00,0.81,-0.19,NaN,0.08
56,ctu-stats,1,4,8,13,8,16,0,3,3,1.50,3,1.50,0,0.00,10,3.25,12,4.00,2,0.75,0.23,0.29,0.05,0.62,0.50,-0.12,NaN,0.12
59,ctu-toxicology,1,0,4,5,3,5,-1,0,2,1.00,1,0.67,-1,-0.33,3,2.50,5,3.33,2,0.83,0.42,0.83,0.42,0.80,0.60,-0.20,1.00,0.25
49,ctu-sales,1,0,4,3,3,3,-1,0,2,1.12,1,0.67,-1,-0.46,3,1.50,2,2.00,-1,0.50,0.25,0.50,0.25,1.33,1.00,-0.33,1.00,0.25
46,ctu-premiereleague,1,1,4,5,3,5,-1,0,2,1.00,1,0.67,-1,-0.33,3,2.50,4,3.33,1,0.83,0.42,0.83,0.42,0.80,0.60,-0.20,1.00,0.25
2,ctu-airline,1,0,19,33,18,528,-1,495,2,1.80,1,0.94,-1,-0.85,33,3.47,128,58.67,95,55.19,0.10,1.73,1.63,0.58,0.03,-0.54,1.00,0.05
15,ctu-credit,1,1,8,9,7,9,-1,0,3,1.66,2,1.35,-1,-0.31,5,2.25,6,2.57,1,0.32,0.16,0.21,0.05,0.89,0.78,-0.11,1.00,0.12
0,ctu-accidents,0,1,3,3,3,3,0,0,1,0.67,1,0.67,0,0.00,2,2.00,2,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
6,ctu-biodegradability,0,2,5,5,5,5,0,0,3,1.44,3,1.44,0,0.00,4,2.00,4,2.00,0,0.00,0.25,0.25,0.00,1.00,1.00,0.00,NaN,0.00
5,ctu-basketballwomen,0,2,8,8,8,8,0,0,4,1.94,4,1.94,0,0.00,6,2.00,6,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
4,ctu-basketballmen,0,2,9,9,9,9,0,0,5,2.27,5,2.27,0,0.00,5,2.00,5,2.00,0,0.00,0.12,0.12,0.00,1.00,1.00,0.00,NaN,0.00
3,ctu-atherosclerosis,0,0,4,3,4,3,0,0,2,1.12,2,1.12,0,0.00,3,1.50,3,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
11,ctu-classicmodels,0,2,8,8,8,8,0,0,6,2.38,6,2.38,0,0.00,4,2.00,4,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
12,ctu-cora,0,1,3,3,3,3,0,0,2,0.89,2,0.89,0,0.00,3,2.00,3,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
9,ctu-cde,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
7,ctu-bupa,0,1,9,8,9,8,0,0,3,1.73,3,1.73,0,0.00,7,1.78,7,1.78,0,0.00,0.11,0.11,0.00,1.12,1.12,0.00,NaN,0.00
21,ctu-employee,0,2,6,6,6,6,0,0,3,1.44,3,1.44,0,0.00,4,2.00,4,2.00,0,0.00,0.20,0.20,0.00,1.00,1.00,0.00,NaN,0.00
23,ctu-expenditures,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
25,ctu-fnhk,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
24,ctu-financial,0,1,8,8,8,8,0,0,3,1.72,3,1.72,0,0.00,5,2.00,5,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
27,ctu-geneea,0,4,19,20,19,20,0,0,7,3.02,7,3.02,0,0.00,5,2.11,5,2.11,0,0.00,0.06,0.06,0.00,0.95,0.95,0.00,NaN,0.00
28,ctu-genes,0,1,3,3,3,3,0,0,2,0.89,2,0.89,0,0.00,3,2.00,3,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
29,ctu-gosales,0,1,5,4,5,4,0,0,3,1.44,3,1.44,0,0.00,3,1.60,3,1.60,0,0.00,0.20,0.20,0.00,1.25,1.25,0.00,NaN,0.00
26,ctu-ftp,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
14,ctu-craftbeer,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
13,ctu-countries,0,1,4,3,4,3,0,0,3,1.25,3,1.25,0,0.00,2,1.50,2,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
17,ctu-dcg,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
16,ctu-dallas,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
18,ctu-diabetes,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
19,ctu-dunur,0,16,17,32,17,32,0,0,2,1.77,2,1.77,0,0.00,32,3.76,32,3.76,0,0.00,0.12,0.12,0.00,0.53,0.53,0.00,NaN,0.00
20,ctu-elti,0,10,11,20,11,20,0,0,2,1.65,2,1.65,0,0.00,20,3.64,20,3.64,0,0.00,0.18,0.18,0.00,0.55,0.55,0.00,NaN,0.00
10,ctu-chess,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
38,ctu-mooney,0,67,68,134,68,134,0,0,2,1.94,2,1.94,0,0.00,134,3.94,134,3.94,0,0.00,0.03,0.03,0.00,0.51,0.51,0.00,NaN,0.00
36,ctu-mesh,0,6,29,33,29,33,0,0,3,1.93,3,1.93,0,0.00,32,2.28,32,2.28,0,0.00,0.04,0.04,0.00,0.88,0.88,0.00,NaN,0.00
35,ctu-legalacts,0,2,5,5,5,5,0,0,3,1.44,3,1.44,0,0.00,4,2.00,4,2.00,0,0.00,0.25,0.25,0.00,1.00,1.00,0.00,NaN,0.00
34,ctu-lahman,0,10,25,31,25,31,0,0,6,2.60,6,2.60,0,0.00,14,2.48,14,2.48,0,0.00,0.05,0.05,0.00,0.81,0.81,0.00,NaN,0.00
32,ctu-hockey,0,8,22,26,22,26,0,0,4,2.08,4,2.08,0,0.00,14,2.74,14,2.74,0,0.00,0.06,0.06,0.00,0.85,0.85,0.00,NaN,0.00
33,ctu-imdb,0,2,7,6,7,6,0,0,5,2.04,5,2.04,0,0.00,3,1.71,3,1.71,0,0.00,0.14,0.14,0.00,1.17,1.17,0.00,NaN,0.00
31,ctu-hepatitis,0,3,7,6,7,6,0,0,4,1.96,4,1.96,0,0.00,3,1.71,3,1.71,0,0.00,0.14,0.14,0.00,1.17,1.17,0.00,NaN,0.00
30,ctu-grants,0,5,12,11,12,11,0,0,4,2.31,4,2.31,0,0.00,6,1.83,6,1.83,0,0.00,0.08,0.08,0.00,1.09,1.09,0.00,NaN,0.00
45,ctu-pima,0,0,9,8,9,8,0,0,2,1.58,2,1.58,0,0.00,8,1.78,8,1.78,0,0.00,0.11,0.11,0.00,1.12,1.12,0.00,NaN,0.00
40,ctu-musklarge,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
47,ctu-restbase,0,1,3,3,3,3,0,0,1,0.67,1,0.67,0,0.00,2,2.00,2,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
50,ctu-samegen,0,3,4,6,4,6,0,0,2,1.12,2,1.12,0,0.00,6,3.00,6,3.00,0,0.00,0.50,0.50,0.00,0.67,0.67,0.00,NaN,0.00
51,ctu-sap,0,0,5,3,5,3,0,0,2,1.06,2,1.06,0,0.00,3,1.50,3,1.50,0,0.00,0.15,0.15,0.00,1.67,1.67,0.00,NaN,0.00
41,ctu-musksmall,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
42,ctu-mutagenesis,0,1,3,3,3,3,0,0,2,0.89,2,0.89,0,0.00,3,2.00,3,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
39,ctu-movielens,0,3,7,6,7,6,0,0,4,1.96,4,1.96,0,0.00,3,1.71,3,1.71,0,0.00,0.14,0.14,0.00,1.17,1.17,0.00,NaN,0.00
54,ctu-sfscores,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
53,ctu-seznam,0,0,4,3,4,3,0,0,2,1.12,2,1.12,0,0.00,3,1.50,3,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
52,ctu-satellite,0,32,36,65,36,65,0,0,4,1.90,4,1.90,0,0.00,34,3.61,34,3.61,0,0.00,0.05,0.05,0.00,0.55,0.55,0.00,NaN,0.00
55,ctu-shakespeare,0,1,4,3,4,3,0,0,3,1.25,3,1.25,0,0.00,2,1.50,2,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
58,ctu-thrombosis,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00
57,ctu-studentloan,0,1,10,9,10,9,0,0,3,1.76,3,1.76,0,0.00,8,1.80,8,1.80,0,0.00,0.10,0.10,0.00,1.11,1.11,0.00,NaN,0.00
60,ctu-tpcc,0,3,9,10,9,10,0,0,4,1.98,4,1.98,0,0.00,3,2.22,3,2.22,0,0.00,0.14,0.14,0.00,0.90,0.90,0.00,NaN,0.00
61,ctu-tpcd,0,1,8,8,8,8,0,0,4,1.91,4,1.91,0,0.00,3,2.00,3,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
63,ctu-tpch,0,2,8,8,8,8,0,0,4,1.91,4,1.91,0,0.00,3,2.00,3,2.00,0,0.00,0.14,0.14,0.00,1.00,1.00,0.00,NaN,0.00
64,ctu-triazine,0,0,2,1,2,1,0,0,1,0.50,1,0.50,0,0.00,1,1.00,1,1.00,0,0.00,0.50,0.50,0.00,2.00,2.00,0.00,NaN,0.00
65,ctu-uwcse,0,2,4,4,4,4,0,0,3,1.25,3,1.25,0,0.00,3,2.00,3,2.00,0,0.00,0.33,0.33,0.00,1.00,1.00,0.00,NaN,0.00
66,ctu-visualgenome,0,2,6,5,6,5,0,0,4,1.72,4,1.72,0,0.00,3,1.67,3,1.67,0,0.00,0.17,0.17,0.00,1.20,1.20,0.00,NaN,0.00
67,ctu-voc,0,0,8,7,8,7,0,0,2,1.53,2,1.53,0,0.00,7,1.75,7,1.75,0,0.00,0.12,0.12,0.00,1.14,1.14,0.00,NaN,0.00
68,ctu-walmart,0,0,4,3,4,3,0,0,3,1.25,3,1.25,0,0.00,2,1.50,2,1.50,0,0.00,0.25,0.25,0.00,1.33,1.33,0.00,NaN,0.00
69,ctu-webkp,0,1,3,3,3,3,0,0,2,0.89,2,0.89,0,0.00,3,2.00,3,2.00,0,0.00,0.50,0.50,0.00,1.00,1.00,0.00,NaN,0.00
70,ctu-world,0,0,3,2,3,2,0,0,2,0.89,2,0.89,0,0.00,2,1.33,2,1.33,0,0.00,0.33,0.33,0.00,1.50,1.50,0.00,NaN,0.00